version: "3"

services:
  node:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: store-crud_api
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: database
      MYSQL_PORT: 3306
    depends_on:
      - database

  database:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: storedb
    ports:
      - "33060:3306"
